### ISSUE TITLE
Reduce the slam's base damage

### ISSUE THREAD

**Issue by MightyW0lf** [AndrewToaster/LoadersHeavySlam#1]
I like the idea of this mod, but the slam is strong by itself already. Reducing the base damage so it's weaker than vanilla when Loader is not falling (and stronger than vanilla when Loader *is* falling) would make this more balanced.

Or at least adding configuration for the skill's base damage coefficient so it can be configured.

**Comment by AndrewToaster** [comment]
I see what you mean, I didn't have time to test it properly in a long run. I will look into this. My idea right now is to add a % value in config that will take the base damage and scale it.

> Or at least adding configuration for the skill's base damage coefficient so it can be configured.

For now, there is a config value called 'DamageSpeedCoef'
![image](https://user-images.githubusercontent.com/29014953/124378683-fe14d680-dcb2-11eb-8335-60c122af416a.png)
You can also tweak the minimal speed required to start scaling

**Comment by AndrewToaster** [comment]
Added baseValue coefficients
![image](https://user-images.githubusercontent.com/29014953/124380880-9f098e80-dcbf-11eb-96e9-ca28cb9f8733.png)

I will update other stuff and release a new version on thunderstore.

*Closing for now*
